export const SCREENS = {
  HOME: 'HOME',
  HOME2: 'HOME2',
  SVIEW: 'SVIEW',
  SCVIEW: 'SCVIEW',
  FLIST: 'FLIST',
  SLIST: 'SLIST',
  SETTINGS: 'SETTINGS',
};

export const STORAGE = {
  INPUT_VALUE: 'INPUT_VALUE'
};